### ISSUE TITLE
Blog/appointment updated

### ISSUE THREAD

**Issue by muellale** [Jubeki/doctor-olivier-medical-practice#10]
We have adapted the blog accordingly and pushed the appointment page. It should be mentioned that we have set up the link to appointments.xml of appointment.md. however, the xml is not displayed because it is not well formed. 

In addition, it should be said that we are finished with all the pages (with the exception of a few small things) and it would be very nice if you could give us feedback on this.

Kindly regards

**Comment by ghost** [comment]
We actually did some validity-checking of the XML files before submission.. and even now when I check the two XML documents in the xml folder using e.g. xmlstarlet (`xmlstarlet val -d blog.dtd blog.xml`), it reports both documents as valid. Please look back into this issue and if there really is a problem with the XML files, feel free to report what changes need to be made to them.

Regarding the blog and subpages:
* The popular post buttons don't do anything when clicked
* The "Popular Post" heading should be "Popular Posts", since there's multiple posts below it
* The "breath of fresh air" and "annual checkups" articles have paragraphs, which however still look like a wall of text despite the formatting. I think you should make it so each paragraph has some space between it.
* The blog subpages don't display the fitting image yet, and they also don't have a "further reading" or "Related Links" section with additional links (as given in the xml file under attachments) yet. Please add those to the design, too.

The make an appointment page looks good to me. But I noticed that after I input my birthdate and scroll down, the little "x" from the birthdate field is shown above the navbar. Of course, that's a little strange. Maybe you can find a way to prevent that from happening.
