### ISSUE TITLE
Blog layout

### ISSUE THREAD

**Issue by muellale** [Jubeki/doctor-olivier-medical-practice#7]
Pls let us know, if the updated layout of the blog is ok. We have tried to adjust your expectations accordingly. (read-more Button, no lines around the sections)

We decided to keep the second column with its opportunities. (about me is a nice spot for dr. oliviers introduction, popular posts and social media buttons complete the overall picture of the blog) 

Kind regards

**Comment by ghost** [comment]
I'm fairly satisfied with the current blog design. Just a few more considerations:
* The "read more" buttons should be capitalized instead ("Read More")
* The "Read More" buttons should have a bit more spacing from the text. I'd also like it if they were a little "slimmer", especially in the vertical direction
* I like that the about me is displayed on the blog, however it looks like a big wall of text on my 720p screen. Screenshot below. Maybe you can find a way to prevent that?
* The "About Me" heading should have more spacing to separate it from the text below it
* Maybe it makes sense to have a slight border around the images (except the corona one obviously, since that one blends into the page nicely).

![Screenshot](https://user-images.githubusercontent.com/7274045/104106454-4cbe5680-52b6-11eb-84f5-0a53f1c591bf.png)
