### ISSUE TITLE
Final thoughts

### ISSUE THREAD

**Issue by carlomatik** [Jubeki/doctor-olivier-medical-practice#8]
Hello @FM-2018 @Jubeki ,

please consider the final state of the following pages:
every page except: index, appointment-booking, blog
and tell us your final thoughts on all of them.  If you require additional changes for those pages this is the last opportunity to voice any feedback.

Kind regards

**Comment by ghost** [comment]
Hello @carlomatik, @muellale,

I have looked at the following pages:
* Contact Us
* Covid-19
* Our Team
* Our Services
* Data Protection Notice

If there's another page that you already deem final, please say so!

So, some feedback:

## Data Protection Notice

* It would be desirable if the headings (1. About Olivier's Medical Practice, 2. ...) stood out more by formatting

# Contact Us

* This page looks fine to me in general
* Maybe you could introduce our primary color into the table head somehow? Set it as the background, set it as the text color, whatever looks good. If none of it looks good, feel free to come back to us with that info.

## Covid-19

* This page looks good in general
* The "Current Developments" heading is a bit too large for my taste. It would make sense to have both this heading and the "WHAT YOU NEED TO KNOW" heading in the same style.

## Our Team

* The "Scroll down to learn more about our great team" message is not immediately visible on my 720p screen. It only comes into view after scrolling, at which point it's no longer a necessary information
* It seems like the page is broken on certain versions of Firefox and derivatives, such as e.g. Palemoon or Waterfox. There's a huge gap between the team members and the footer comes into view too early, moving over the content as one scrolls down. It's as if something was causing the team member divisions to be higher than their content needed them to be..
* I think it would add a lot of dynamic and separation if you switched the image and text with every second team member, or if you made the team member divisions stand out from the rest of the page by giving them a nice background (like a box that contains them and their information)

## Our Services

* This page does not look very formatted yet, the text looks like default HTML. How about the usage of headings to better separate services and examinations, and some icons instead of bullet points to better illustrate the services?
* The images on the side still clip under the navbar on both my 720p and 1080p screen
* Why is the area for the text on the left so small? This leaves a lot of unused space in the middle. Wouldn't it make sense to extend it a little, which might also make the text more readable?

## General

* It seems the logo in the header is still just a png. That's fine for now, but don't forget to include an SVG version of it some time in the future
* Why does the copyright notice in the footer have a hover effect? At least for me, this always tricks me into thinking that it is a clickable button, even though it is not. I'd prefer it to not have a hover effect.
* "opening hours" in the header should be capitalized ("Opening hours")

**Comment by carlomatik** [comment]
Hello @FM-2018 @Jubeki ,

your feedback has been implemented with the following exceptions:
- _ It seems like the page is broken on certain versions of Firefox and derivatives_ we could not recreate this nor did we have any issues on any tested application / dimensions, hence why we did not took this into consideration.
- Our Services is not further formatted since the given content does not allow much to format, it is just plain text with not much headers are anything of that kind.
- The Logo in the header is and will remain a png since it was never stated anywhere that this is to be modelled as an svg, if we are wrong with this assumption please provide the source that states otherwise. Since the logo uses a strange font which is not given remodelling the logo into an svg would be extremely time consuming and it would not benefit the website at its current state. If you can provide us with the used font or the corresponding svg we will of course implement it.

Kind regards

**Comment by ghost** [comment]
Hey @carlomatik and @muellale ,

* Which applications are you testing and designing for exactly? The problems occur e.g. on Pale Moon 28.17.0 or Waterfox Classic 2020.12. Those browsers aren't widely used at all, so it's alright you (probably) don't design for them. It just seemed like the problem could be solved quickly by removing the "height" property from the des-photo and des-photo2 classes (it's apparently ignored by the new Firefox versions).
* Please note that you do not have to include the example content exactly as it is written. You are of course allowed to add headings or change phrases and mark them up as a heading (A little bigger, bold font). Good headings would be "General Services", "Examinations", "Specialized Services", each to be added before the "We provide the following services", "In addition to a thorough physical examination..." and "Structued treatment programs ..." phrases. For further formatting, it would still be nice if you looked for some additional icons, but of course we understand that this might be difficult due to time constraints, so we won't insist on it.
* You are right, we haven't made this a requirement, as there's already some SVG content on the Covid-19 page. In that case, no further action is required from you.

Please answer which applications you're designing for and if you find the time, maybe you can take another look at the second point. But of course, the implementation of the remaining pages should be the focus for now.

**Comment by carlomatik** [comment]
Hello @FM-2018 ,

- we are testing for the following: Safari / Chrome on newest iOS + MacOS & Firefox on Windows 10, if there is time remaining we can look into removing the height property of said files however we will only be able to test for if nothing changed for us since we can't test for said "Pale Moon 28.17.0 or Waterfox Classic 2020.12"
- we will take a look into adding some headers et cetera to the services pages to meet the voiced expectations

We will further try to push a final version of the complete website this evening in which case we would appreciate a final feedback to be implemented tomorrow. Because of the time shortage for our team (I had to work on my bachelor thesis over the holidays and Alex had other assignements) we still hope that you will like and approve our final product, but thats another issue to come.

Kind regards
